org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.21.1
loader_version = 0.17.2
parchment_version = 1.21:2024.07.28

# Mod Properties
mod_version=1.0.0
maven_group=com.phantomwing.choppersdelight
archives_base_name=choppersdelight

# Dependencies
fabric_version=0.116.6+1.21.1
appleskin_version = mc1.21-3.0.5
jei_version = 19.9.1.125
farmersdelight_version = 3.2.0

terrablender_version=4.1.0.8
geckolib_version=4.7.6
corgilib_version=5.0.0.7
ohthetreesyoullgrow_version=5.0.14
biomeswevegone_version=2.4.6
glitchcore_version=2.1.0.0
biomesoplenty_version=21.1.0.12

# Debug props
include_biomeswevegone=true
include_biomesoplenty=true