# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mappings_channel=parchment
mappings_version=2023.09.03-1.20.1

## Mod info
mod_version=1.0.1
mod_id=choppersdelight
mod_group_id=com.phantomwing.choppersdelight
mod_license=MIT License
mod_name=Chopper's Delight
mod_description=An add-on for Farmer's Delight that adds Cutting Board variants for different wood types, and the ability to decorate them using banners.
mod_authors=PhantomWing

# Main dependencies
farmersdelight_version=5051242

# Compatibility
terrablender_version=3.0.1.10
geckolib_version=4.8.2
corgilib_version=4.0.3.5
ohthetreesyoullgrow_version=1.4.2
biomeswevegone_version=1.7.1
glitchcore_version=0.0.1.1
biomesoplenty_version=19.0.0.96

# Other dependencies
appleskin_version=mc1.20.1-2.5.0
include_appleskin=true
jei_version=15.0.0.12

# Debug props
include_biomeswevegone=true
include_biomesoplenty=true