# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.21.1
loader_version = 0.18.0
parchment_version = 2024.11.17

# Mod Properties
mod_version=1.0.2
maven_group=com.phantomwing.choppersdelight
mod_id=choppersdelight

# Dependencies
fabric_version = 0.116.7+1.21.1
appleskin_version = mc1.21-3.0.5
jei_version = 19.9.1.125
farmersdelight_version = 3.2.2

terrablender_version=4.1.0.8
geckolib_version=4.7.6
corgilib_version=5.0.0.7
ohthetreesyoullgrow_version=5.0.14
biomeswevegone_version=2.4.6
glitchcore_version=2.1.0.0
biomesoplenty_version=21.1.0.12

# Debug props
include_biomeswevegone=true
include_biomesoplenty=true